services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - app-data:/app/.data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env

volumes:
  app-data: