# fly.toml app configuration file generated for mcp-anywhere-rob on 2025-10-16T00:17:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mcp-anywhere-rob'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/.data'
  DOCKER_HOST = 'unix:///var/run/docker.sock'
  LOG_LEVEL = 'DEBUG'
  MCP_PATH = '/mcp'
  OAUTH_USER_ALLOWED_DOMAIN = 'locomotive.agency'
  SERVER_URL = 'https://mcp-anywhere-rob.fly.dev'
  WEB_PORT = '8000'

[[mounts]]
  source = 'mcp_anywhere_data'
  destination = '/.data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
