site_name: MCP Anywhere
site_description: A unified gateway for Model Context Protocol servers - discover, configure, and access MCP tools through a single endpoint
site_url: https://mcpanywhere.com
repo_url: https://github.com/locomotive-agency/mcp-anywhere
repo_name: locomotive-agency/mcp-anywhere
copyright: Copyright &copy; 2024 Locomotive Agency

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.follow
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      separator: '[\s\-\.]+'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/locomotive-agency/mcp-anywhere

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Deployment: deployment.md